name: CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn deploy
